module.exports = Object.freeze({
    ARK: 'ark',
    //???: 'or',
    SQUAD_EDITOR: 'squad',
    //???: 'odin',
    //???: 'ut',
    //???: 'vpr',
    CONAN_EXILES: 'conanexiles',
    HELLO_NEIGHBOR: 'helloneighbor',
    VR_FUN_HOUSE: 'vrfunhouse',
	FORTNITE: 'fn',
	BUS_SIMULATOR_2018: 'bussim18',
	DARK_AND_LIGHT_EDITOR: 'darkandlight',
	CONTAN_EXILES: 'conanexiles',
	MARS_2030: 'mars2030',
	PIXARK: 'pixark',
	SHOWMAKER: 'showmaker',
	//???: 'min',
	//???: 'morpho',
	UNREAL_TOURNAMENT: 'ut'
});